{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./distrobox.nix
    ./env.nix
    ./gc.nix
    ./home-manager.nix
    ./hyprland.nix
    ./keyboard.nix
    ./net.nix
    ./nh.nix
    ./nix.nix
    ./plymouth.nix
    ./virt.nix
    ./regreet.nix
    ./steam.nix
    ./stylix.nix
    ./tailscale.nix
    ./thunar.nix
    ./user.nix
    ./wireshark.nix
  ];
}
