{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./distrobox.nix
    ./env.nix
    ./firewall.nix
    ./flatpak.nix
    ./fonts.nix
    ./gc.nix
    ./home-manager.nix
    ./kde.nix
    ./keyboard.nix
    ./net.nix
    ./nh.nix
    ./nix.nix
    ./plymouth.nix
    ./services.nix
    ./sops.nix
    ./sql.nix
    ./steam.nix
    ./stylix.nix
    ./sunshine
    ./tailscale.nix
    ./thunar.nix
    ./user.nix
    ./virt.nix
    ./wireshark.nix
  ];
}
