{ pkgs, inputs, ... }:
{
  nixpkgs.config.allowUnfree = true;

  nixpkgs.config.permittedInsecurePackages = [
    "electron-33.4.11"
  ];

  home.packages = with pkgs; [
    adwsteamgtk
    age
    airshipper
    android-tools
    anydesk
    appimage-run
    azahar
    bitwarden-desktop
    bottom
    brave
    brightnessctl
    cartridges
    cliphist
    deluge
    dolphin-emu
    dosbox
    feishin
    ffmpeg
    ffmpegthumbnailer
    fzf
    gamescope
    gedit
    gnome-disk-utility
    goverlay
    grim
    heroic
    htop
    hyprpanel
    hyprshot
    imv
    jellyfin-media-player
    inputs.zen-browser.packages."${pkgs.system}".beta
    jellyfin-rpc
    kdePackages.akonadi
    kdePackages.kdenlive
    khal
    krita
    libnotify
    libreoffice
    linux-wallpaperengine
    lutris
    mangohud
    megasync
    melonDS
    mono
    moonlight-qt
    mpv
    networkmanagerapplet
    octave
    openvpn
    p7zip
    pavucontrol
    playerctl
    ppsspp
    prismlauncher
    protontricks
    protonup-qt
    retroarch
    rpcs3
    rsync
    ryubing
    sgdboop
    slurp
    sops
    steam-rom-manager
    teamspeak6-client
    tree
    ueberzugpp
    umu-launcher
    unrar
    unzip
    vesktop
    vlc
    vscode
    vulkan-tools
    wget
    wineWowPackages.staging
    winetricks
    wl-clipboard
    xdelta
    xivlauncher
    yad
    zed
    zenity
    zip
  ];
}
